### ISSUE TITLE
xlsmapper 性能が遅すぎる

### ISSUE THREAD

**Issue by tjx0722** [mygreen/xlsmapper#118]
<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by mygreen** [comment]
@tjx0722 

以下の点が不明なので提示して頂けるとありがたいです。
- 読み込み／書き込みがのどちらが遅いのか。
- どのようなデータを使用しているのか。
  - 使用しているデータのサンプルがあれば提供をお願いします。
- 性能の目標値。

**Comment by mygreen** [comment]
返答がないので、クローズします。
