### ISSUE TITLE
XMLファイルによるマッピングが動作しないのではないでしょうか

### ISSUE THREAD

**Issue by puu123** [mygreen/xlsmapper#82]
失礼いたします。

XlsLoaderの下記部分は直接クラスからアノテーションの情報を取得されていますが、
XMLファイルによるマッピングもサポートされるなら、
AnnotationReaderから取得しなければならないような気がしますが如何でしょうか。

~~~
XlsLoader.java#L144
final XlsSheet sheetAnno = clazz.getAnnotation(XlsSheet.class);
　　　↓　
XlsSheet sheetAnno = annoReader.getAnnotation(clazz, XlsSheet.class);
~~~

的外れなようであれば申し訳ありません。<(_  _)>

**Comment by mygreen** [comment]
- v1.4.4として修正を取り込みリリースしました。
